# Generated by Django 5.1 on 2024-12-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_id',
            field=models.CharField(default=10000, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
